import tailwindcss from '@tailwindcss/vite'
// Generated by scripts/wp-migrate: old flat post URL (/<slug>) → /news/<slug>.
import postRedirects from './app/redirects.json'

// Old WordPress post URLs → their new /news/<slug> home, as 301 route rules.
const newsRedirects = Object.fromEntries(
  Object.entries(postRedirects).map(([from, to]) => [
    from,
    { redirect: { to, statusCode: 301 } },
  ]),
)

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: [
    '@nuxt/content',
  ],
  css: ['~/assets/css/main.css'],
  vite: {
    plugins: [
      tailwindcss(),
    ],
  },
  app: {
    head: {
      htmlAttrs: { lang: 'en-GB' },
      title: 'LAS UNISON — London Ambulance Service UNISON Branch',
      meta: [
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        {
          name: 'description',
          content:
            'The UK’s biggest ambulance branch. We represent, protect and stand up for London Ambulance Service staff — almost 7,000 members strong.',
        },
        { name: 'theme-color', content: '#5E22A6' },
      ],
      link: [
        { rel: 'icon', href: '/favicon.ico', sizes: '48x48 32x32 16x16' },
        { rel: 'icon', type: 'image/png', href: '/favicon-32.png', sizes: '32x32' },
        { rel: 'icon', type: 'image/png', href: '/favicon-16.png', sizes: '16x16' },
        { rel: 'apple-touch-icon', href: '/apple-touch-icon.png' },
        { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
        { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' },
        {
          rel: 'stylesheet',
          href: 'https://fonts.googleapis.com/css2?family=Archivo:wght@500;600;700;800;900&family=IBM+Plex+Mono:wght@400;500;600&family=Public+Sans:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400&display=swap',
        },
      ],
    },
  },
  routeRules: {
    // Migrated news posts: old flat URL → /news/<slug> (482 rules, generated).
    ...newsRedirects,
    // Old WordPress URLs → new canonical legal paths (hand-maintained; win over the above).
    // Branch officers + reps were two separate WordPress pages; both now live on /branch.
    '/branch-officers':                        { redirect: { to: '/branch', statusCode: 301 } },
    '/branch-officers/branch-representatives':  { redirect: { to: '/branch#representatives', statusCode: 301 } },
    '/branch-representatives':                  { redirect: { to: '/branch#representatives', statusCode: 301 } },
    '/privacy-policy':          { redirect: { to: '/legal/privacy-policy', statusCode: 301 } },
    '/about-us/privacy-policy': { redirect: { to: '/legal/privacy-policy', statusCode: 301 } },
    '/about-us/cookie-policy':  { redirect: { to: '/legal/cookie-policy',  statusCode: 301 } },
    '/legal-services':          { redirect: { to: '/legal/legal-services',  statusCode: 301 } },
    // Merged / pruned during the content review: duplicate, incomplete or
    // obsolete pages now point to their canonical home (URLs preserved).
    '/las-unison-branch-rules': { redirect: { to: '/branch-rules',          statusCode: 301 } },
    '/stewards-directory':      { redirect: { to: '/find-a-rep',            statusCode: 301 } },
    '/application-for-course':  { redirect: { to: '/education',             statusCode: 301 } },
    '/lasunison-net':           { redirect: { to: '/about-us/contact-us',   statusCode: 301 } },
    '/lasunison-com-e-mail':    { redirect: { to: '/about-us/contact-us',   statusCode: 301 } },
    // Old document-library + links pages are now folded into the Resources hub.
    '/documents':               { redirect: { to: '/resources', statusCode: 301 } },
    '/document-database-new':   { redirect: { to: '/resources', statusCode: 301 } },
    '/links-page':              { redirect: { to: '/resources', statusCode: 301 } },
    '/links-page-2':            { redirect: { to: '/resources', statusCode: 301 } },
    // Empty WordPress stubs that duplicate the new IA → their canonical home.
    '/home':                    { redirect: { to: '/',          statusCode: 301 } },
    '/posts':                   { redirect: { to: '/news',      statusCode: 301 } },
    '/about':                   { redirect: { to: '/about-us',  statusCode: 301 } },
    // Bulletins are no longer a separate section — they live as documents in the
    // Resources library now, so the old hub + per-topic pages redirect there.
    '/bulletins':                  { redirect: { to: '/resources', statusCode: 301 } },
    '/bulletins-2':                { redirect: { to: '/resources', statusCode: 301 } },
    '/general-bulletins':          { redirect: { to: '/resources', statusCode: 301 } },
    '/education-bulletins':        { redirect: { to: '/resources', statusCode: 301 } },
    '/equalities-bulletins':       { redirect: { to: '/resources', statusCode: 301 } },
    '/health-safety-bulletins':    { redirect: { to: '/resources', statusCode: 301 } },
    '/labour-link-bulletins':      { redirect: { to: '/resources', statusCode: 301 } },
    '/membership-bulletins':       { redirect: { to: '/resources', statusCode: 301 } },
    '/welfare-bulletins':          { redirect: { to: '/resources', statusCode: 301 } },
    '/retired-members-bulletins':  { redirect: { to: '/resources', statusCode: 301 } },
    '/sector-bulletins':           { redirect: { to: '/resources', statusCode: 301 } },
    '/branch-chair-bulletins':     { redirect: { to: '/resources', statusCode: 301 } },
    '/branch-secretary-bulletins': { redirect: { to: '/resources', statusCode: 301 } },
    '/other-bulletins':            { redirect: { to: '/resources', statusCode: 301 } },
  },
  devtools: { enabled: true },
  compatibilityDate: '2024-04-03',
})
